name: Deploy Hugo site to GitHub Pages

on:
  push:
    branches:
      - main  # 替换为你的默认分支名，通常是 main 或 master
  workflow_dispatch:

# 设置权限
permissions:
  contents: read
  pages: write
  id-token: write

# 只允许一次并发部署，跳过中间队列的运行
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # 构建作业
  build:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.146.0  # 使用最新版本
    steps:
      - name: 安装 Hugo CLI
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb          

      - name: 安装 Dart Sass
        run: sudo snap install dart-sass

      - name: 检出源代码
        uses: actions/checkout@v4
        with:
          submodules: recursive  # 拉取包含主题在内的子模块
          fetch-depth: 0         # 拉取所有历史记录，这对某些 Hugo 功能很重要

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5

      - name: 构建 Hugo 站点
        run: |
          hugo --minify --baseURL "${{ steps.pages.outputs.base_url }}/"
          
      - name: 上传构建产物
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  # 部署作业
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: 部署到 GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4